name: chat2db

services:
  mysql:
    image: mysql:8.0-debian
    networks:
      - chatdb-network
    environment:
      MYSQL_ROOT_PASSWORD: root@123456
      MYSQL_DATABASE: movies
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    networks:
      - chatdb-network
    ports:
      - "7860:7860"
    volumes:
      - ./logs:/app/logs
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - OLLAMA_API_URL=${OLLAMA_API_URL}
      - OLLAMA_CHAT_MODEL=${OLLAMA_CHAT_MODEL}
      - OLLAMA_CODE_MODEL=${OLLAMA_CODE_MODEL}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  chatdb-network:
    name: chat2db-network
    driver: bridge
