name: chat2db

services:
  mysql:
    image: mysql:8.0-debian
    networks:
      - chatdb-network
    environment:
      MYSQL_ROOT_PASSWORD: root@123456
      MYSQL_DATABASE: movies
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongodb:
    image: mongo
    networks:
      - chatdb-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root@123456
      MONGO_INITDB_DATABASE: movies
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    networks:
      - chatdb-network
    ports:
      - "7860:7860"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - OLLAMA_API_URL=${OLLAMA_API_URL}
      - OLLAMA_CHAT_MODEL=${OLLAMA_CHAT_MODEL}
      - OLLAMA_CODE_MODEL=${OLLAMA_CODE_MODEL}
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy

volumes:
  mysql_data:
  mongodb_data:

networks:
  chatdb-network:
    name: chat2db-network
    driver: bridge
